# Dockerfile generated by Gemini 2.5 Pro
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code
COPY . .

# Command to run the Uvicorn server
# It must listen on host 0.0.0.0 and a specific port (8080 is common)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]